#! /usr/bin/perl -w

use strict;
use Getopt::Long;
use lib '.';
use DetectRoll;

GetOptions('debug'=>\$DetectRoll::debug) or die;

my $dir = shift;
my $dr=DetectRoll->new($dir);

#print $dr->has_roll ? "yes\n" : "no\n"; exit;

my ($left,$right) = $dr->find_roll;

print "last image is $left; earliest is $right\n";
